services:
    api:
        build: ./api
        ports:
            - "3010:3000"
        volumes:
            - .:/app
        environment:
            - NODE_ENV=development
            - PORT=3000
        env_file:
            - .env
    web:
        build: ./web
        ports:
            - "8082:8082"
        restart: always
        volumes:
            - /app/node_modules
            - $PWD/web/src:/app/web/src
            - $PWD/web/public:/app/web/public
        environment:
            - NODE_ENV=development
            - PORT=8082
