services:
    api:
        build: ./api
        ports:
            - "3010:3000"
        volumes:
            - .:/app
        environment:
            - NODE_ENV=development
            - PORT=3000
    web:
        build: ./web
        ports:
            - "8082:8080"
        volumes:
            - .:/app
        environment:
            - NODE_ENV=development
            - PORT=8080
